### ISSUE TITLE
请问这个是热部署失败了么？

### ISSUE THREAD

**Issue by GalileoFinchDudi** [jrainlau/markcook#5]
D:\g\markcook\node_modules\webpack-dev-server\bin\webpack-dev-server.js:385
                throw e;
                ^

TypeError: webpack.validateSchema is not a function
    at new Server (D:\g\markcook\node_modules\webpack-dev-server\lib\Server.js:23:33)
    at startDevServer (D:\g\markcook\node_modules\webpack-dev-server\bin\webpack-dev-server.js:378:12)
    at D:\g\markcook\node_modules\webpack-dev-server\bin\webpack-dev-server.js:324:3
    at D:\g\markcook\node_modules\portfinder\lib\portfinder.js:160:14
    at D:\g\markcook\node_modules\async\lib\async.js:52:16
    at D:\g\markcook\node_modules\async\lib\async.js:269:32
    at D:\g\markcook\node_modules\async\lib\async.js:44:16
    at D:\g\markcook\node_modules\portfinder\lib\portfinder.js:122:16
    at Server.onListen (D:\g\markcook\node_modules\portfinder\lib\portfinder.js:45:7)
    at Server.g (events.js:291:16)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! markcook2.0@ dev: `webpack-dev-server --inline --hot`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the markcook2.0@ dev script 'webpack-dev-server --inline --hot'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the markcook2.0 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --inline --hot
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs markcook2.0
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls markcook2.0
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\g\markcook\npm-debug.log

**Comment by GalileoFinchDudi** [comment]
我全局安装了一下webpack，可以了。
npm install webpack -g
